//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoLM15SGFNZ07Driver
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("DemoLM15SGFNZ07Driver.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            compass2 = -28929,
            Jpeg01Normal = -22693,
            Gif01Normal = -4332,
            out1 = 2676,
            cat3 = 5607,
            smile = 12815,
            cat2 = 16938,
            compass = 18208,
            out2 = 22584,
            out0 = 25601,
            cat1 = 28746,
            spotlogo110 = 29922,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            arial8 = -15967,
            arial6 = -14386,
            courier11 = -11131,
            arial10 = 9429,
            arial9 = 12947,
            small = 13070,
            nina14 = 19188,
            ninabd18ppem = 31399,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            String1 = 1228,
        }
    }
}
